package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])  # Apache License 2.0

filegroup(
    name = "testdata",
    srcs = glob([
        "*",
        "*/*",
    ]),
)
