package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])  # Apache License 2.0

exports_files(["LICENSE"])

# KEEP THIS LINE to import nucleus.bzl externally

filegroup(
    name = "testdata",
    srcs = glob([
        "*",
        "*/*",
    ]),
)
