package(
    default_visibility = [
        "//visibility:public",
    ],
)

licenses(["notice"])  # Apache License 2.0

# KEEP THIS LINE to import nucleus.bzl externally

cc_library(
    name = "types",
    hdrs = ["types.h"],
)
